module.exports = [
    'What was the last funny video you saw?',
    'What do you do to get rid of stress?',
    'What is something you are obsessed with?',
    'What three words best describe you?',
    'What would be your perfect weekend?',
    'What’s your favorite number? Why?',
    'What are you going to do this weekend?',
    'What’s the most useful thing you own?',
    'What’s your favorite way to waste time?',
    'Do you have any pets? What are their names?',
    'What did you do last weekend?',
    'What is something popular now that annoys you?',
    'What did you do on your last vacation?',
    'Are you very active, or do you prefer to just relax in your free time?',
    'What do you do when you hang out with your friends?',
    'Who is your oldest friend? Where did you meet them?',
    'What’s the best/worst thing about your work/school?',
    'If you had intro music, what song would it be? Why?',
    'What were you really into when you were a kid?',
    'If you could have any animal as a pet, what animal would you choose?',
    'Have you ever saved an animal’s life? How about a person’s life?',
    'If you opened a business, what kind of business would it be?',
    'Who is your favorite entertainer (comedian, musician, actor, etc.)?',
    'Are you a very organized person?',
    'What is the strangest dream you have ever had? (Keep it PG)',
    'Who in your life brings you the most joy?',
    'What is the most annoying habit someone can have?',
    'Where is the most beautiful place you have been?',
    'How often do you stay up past 3 a.m.?',
    'What’s your favorite season? Why?',
    'Which is more important, having a great car or a great house? Why?',
    'What animal or insect do you wish humans could eradicate?',
    'What do you bring with you everywhere you go?',
    'How much time do you spend on the internet? What do you usually do?',
    'Where and when was the most amazing sunset you have ever seen?',
    'Which recent news story is the most interesting?',
    'Where is the worst place you have been stuck for a long time?',
    'If you had to change your name, what would your new name be?',
    'What is something that really annoys you but doesn’t bother most people?',
    'What word or saying from the past do you think should come back?',
    'How should success be measured? And by that measurement, who is the most successful person you know?',
    'If you could learn the answer to one question about your future, what would the question be?',
    'What was the best period of your life so far? What do you think will be the best period of your entire life?',
    'What do you do to improve your mood when you are in a bad mood?',
    'What is the silliest fear you have?',
    'What smell brings back great memories?',
    'What weird or useless talent do you have?',
    'What was the best birthday wish or gift you’ve ever received?',
    'What was the last book you read?',
    'What was your favorite book as a child?',
    'What is the longest book you’ve read?',
    'What is your favorite movie soundtrack?',
    'What song always puts you in a good mood?',
    'Are there any songs that always bring a tear to your eye?',
    'What are the three best apps on your phone?',
    'What do app makers do that really annoys you?',
    'What is the strangest app you have heard of or tried?',
    'What will phones be like in 10 years?',
    'What is the most annoying thing about your phone?',
    'What sports do you like to watch?',
    'Which sports do you like to play?',
    'Do athletes deserve the high salaries they receive? Why or why not?',
    'What restaurant do you eat at most?',
    'What’s the worst fast food restaurant?',
    'What is the best restaurant in your area?',
    'What is the fanciest restaurant you have eaten at?',
    'Where would you like to travel next?',
    'What is the longest plane trip you have taken?',
    'Do you prefer to go off the beaten path when you travel?',
    'What was the most overhyped place you’ve traveled to?',
    'Have you traveled to any different countries? Which ones?',
    'What’s the best thing about traveling? How about the worst thing?',
    'What is your favorite holiday?',
    'What kinds of food do you usually eat on your favorite holiday?',
    'If you could make a holiday, what would it be like? What traditions would it have? What would people eat on your holiday?',
    'What foods do you absolutely hate?',
    'What food looks disgusting but tastes delicious?',
    'What flavor of ice cream do you wish existed?',
    'If you had a personal mascot, what would your mascot be?',
    'If you could call up anyone in the world and have a one-hour conversation, who would you call?',
    'What is the most overrated movie?',
    'Which do you prefer? Books or movies?',
    'Do you like documentaries? Why / why not?',
    'Do you prefer to watch movies in the theater or in the comfort of your own home?',
    'What’s the best show currently on TV?',
    'If you could bring back one TV show that was canceled, which one would you bring back?',
    'Do you like reality TV shows? Why or why not? If so, which ones?',
    'If you were a transformer, what vehicle would you turn into?'
];