module.exports = [
    "What has to be broken before you can use it?",
    "I’m tall when I’m young, and I’m short when I’m old. What am I?",
    "What month of the year has 28 days?",
    "What is full of holes but still holds water?",
    "What question can you never answer yes to?",
    "What is always in front of you but can’t be seen?",
    "There’s a one-story house in which everything is yellow. Yellow walls, yellow doors, yellow furniture. What color are the stairs?",
    "What can you break, even if you never pick it up or touch it?",
    "What goes up but never comes down?",
    "A man who was outside in the rain without an umbrella or hat didn’t get a single hair on his head wet. Why?",
    "What gets wet while drying?",
    "What can you keep after giving to someone?",
    "I shave every day, but my beard stays the same. What am I?",
    "You see a boat filled with people, yet there isn’t a single person on board. How is that possible?",
    "You walk into a room that contains a match, a kerosene lamp, a candle and a fireplace. What would you light first?",
    "A man dies of old age on his 25 birthday. How is this possible?",
    "I have branches, but no fruit, trunk or leaves. What am I?",
    "What can’t talk but will reply when spoken to?",
    "The more of this there is, the less you see. What is it?",
];
