module.exports = [
    "An egg",
    "A candle",
    "All of them",
    "A sponge",
    "Are you asleep yet?",
    "The future",
    "There aren’t any—it’s a one-story house.",
    "A promise",
    "Your age",
    "He was bald.",
    "A towel",
    "Your word",
    "A barber",
    "All the people on the boat are married.",
    "The match",
    "He was born on February 29.",
    "A bank",
    "An echo",
    "Darkness",
];